### ISSUE TITLE
UserCSS

### ISSUE THREAD

**Issue by KraXen72** [myreli/sn-flexoki#1]
please release this as a UserCSS for the web version of Standard Notes, preferrably with a working autoupdate url. Thanks!

**Comment by myreli** [comment]
Hey @KraXen72! It already works on Standard Notes web, and autoupdates trough the plugin manager. Here is an example:

https://github.com/myreli/sn-flexoki/assets/17554234/bd2d9837-2a2b-4dbf-aeeb-b78857d8c17c

Is there something specific that I'm missing?

**Comment by KraXen72** [comment]
oh, sorry. i didn' know you can add plugins to the web version as well, i thought it's only the desktop/mobile app. for now i just copied the css into my userstyle manager, and i made one-two tweaks anyway so the auto-update probably won't be that useful for me. but thanks for the video, and also it shows me how other people use standardnotes! inspiring! i just use it for my private stuff that i can't have in obsidian - diary, dream logs, rants, etc. will look into how else i could use it.

**Comment by myreli** [comment]
No problem, happy to help! 🤗 

Whenever you want, you can explore that structure by clicking "Try live demo" on the website: https://standardnotes.com.
